name: Audit

on:
  push:
    branches: [master]
  pull_request:
    brances: [master]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up GO
      uses: action/setup-go@v2
      with:
        go-version: 1.22

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./..

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run golint
      run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...




